.TH "" "" "" "" ""
.PP
[IMAGE: status (https://img.shields.io/badge/build-fails-red.svg)] #
autobadger > No name given yet
.SS Install
.PP
Install it with
.IP
.nf
\f[C]
npm\ install\ autobadger
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ autobadger\ [\ \-h\ |\ \-\-help\ ]

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ autobadger

Commands:

Arguments:
\f[]
.fi
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Released under the BSD License.
.PP
   *   *   *   *   *
.SH New features
.IP \[bu] 2
produce svg status info about passing build \-\- Jul 25th
15 (../../commit/904602c2b7196fc5949a657d169abde73dc2197e)
